-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT 'b0d8866e9f3e81f1' HASH '1a9167d333f70a3861d377fb733cf11bd498ff75f77808c9b847931580903b34' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."flyway_schema_history"(
    "installed_rank" INTEGER NOT NULL,
    "version" CHARACTER VARYING(50),
    "description" CHARACTER VARYING(200) NOT NULL,
    "type" CHARACTER VARYING(20) NOT NULL,
    "script" CHARACTER VARYING(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" CHARACTER VARYING(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
);               
ALTER TABLE "PUBLIC"."flyway_schema_history" ADD CONSTRAINT "PUBLIC"."flyway_schema_history_pk" PRIMARY KEY("installed_rank");
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.flyway_schema_history;   
INSERT INTO "PUBLIC"."flyway_schema_history" VALUES
(-1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, 'SA', TIMESTAMP '2026-01-09 13:51:07.505329', 0, TRUE),
(1, '1', 'create table books', 'SQL', 'V1__create_table_books.sql', 1668442015, 'SA', TIMESTAMP '2026-01-09 13:51:07.534321', 6, TRUE),
(2, '2', 'add of synopsis', 'SQL', 'V2__add_of_synopsis.sql', 1972870510, 'SA', TIMESTAMP '2026-01-09 13:51:07.545419', 5, TRUE),
(3, '3', 'add of author', 'SQL', 'V3__add_of_author.sql', 523377166, 'SA', TIMESTAMP '2026-01-09 13:51:07.552432', 4, TRUE);             
CREATE INDEX "PUBLIC"."flyway_schema_history_s_idx" ON "PUBLIC"."flyway_schema_history"("success" NULLS FIRST);               
CREATE CACHED TABLE "PUBLIC"."TB_BOOKS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 225) NOT NULL,
    "TITLE" CHARACTER VARYING(255),
    "BOOK_URL" CHARACTER VARYING(255),
    "FOREIGNKEY_USER_ID" BIGINT,
    "SYNOPSIS" CHARACTER VARYING(255),
    "AUTHOR" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."TB_BOOKS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");     
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.TB_BOOKS;
INSERT INTO "PUBLIC"."TB_BOOKS" VALUES
(35, U&'Mang\00e1 Naruto Altered', U&'https://amazom/livros/Mang\00e1+do+naruto', 129, 'TESTE3', 'Masashi Kishimoto'),
(65, U&'Mang\00e1 Naruto teste', U&'https://amazom/livros/Mang\00e1+do+naruto1', 12, 'TESTE34', 'Masashi Kishimoto teste'),
(129, 'Assim Falou Zaratustra', 'https://amazom/livros/Assim+Falou+Zaratustra', 2, 'TESTE4', 'Friedrich Nietzsche'),
(161, 'Assim Falou Zaratustra000', 'https://amazom/livros/Assim+Falou+Zaratustra0000', 2, 'TESTE4000', 'Friedrich Nietzsche000');          
CREATE CACHED TABLE "PUBLIC"."TB_USER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 225) NOT NULL,
    "USERNAME" CHARACTER VARYING(255),
    "AGE" INTEGER,
    "GMAIL" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."TB_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");      
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TB_USER; 
INSERT INTO "PUBLIC"."TB_USER" VALUES
(129, 'Sakura', 17, 'Sakura@gmail.com'),
(193, 'Rodinei', 48, 'RodineiGames@gmail.com'),
(194, U&'Ot\00e1vio', 15, 'otavio@gmail.com');              
ALTER TABLE "PUBLIC"."TB_BOOKS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5F2" UNIQUE NULLS DISTINCT ("SYNOPSIS");  
ALTER TABLE "PUBLIC"."TB_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D1" UNIQUE NULLS DISTINCT ("GMAIL");       
ALTER TABLE "PUBLIC"."TB_BOOKS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5F21" UNIQUE NULLS DISTINCT ("AUTHOR");   
ALTER TABLE "PUBLIC"."TB_BOOKS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5F" UNIQUE NULLS DISTINCT ("BOOK_URL");   
